### ISSUE TITLE
`FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-11-128260e0dc37>'`

### ISSUE THREAD

**Issue by DanielGoldfarb** [gaogaotiantian/watchpoints#14]
```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-11-128260e0dc37> in <module>
----> 1 watch(plt.rcParams['axes.titleweight'])

~/.local/lib/python3.8/site-packages/watchpoints/watch.py in __call__(self, *args, **kwargs)
     26         with self.set_lock:
     27             frame = inspect.currentframe().f_back
---> 28             argnodes = getargnodes(frame)
     29             for node, name in argnodes:
     30                 self.watch_list.append(

~/.local/lib/python3.8/site-packages/watchpoints/util.py in getargnodes(frame)
     41     get the list of arguments of the current line function
     42     """
---> 43     line = getline(frame)
     44     m = re.match(r".*?\((.*)\)", line)
     45     if not m:  # pragma: no cover

~/.local/lib/python3.8/site-packages/watchpoints/util.py in getline(frame)
     17     filename = frame.f_code.co_filename
     18 
---> 19     with open(filename, "r", encoding="utf-8") as f:
     20         lines = f.readlines()
     21         if sys.version_info.minor <= 7:

FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-11-128260e0dc37>'
```

Let me know if you need more information.  Running in jupyter notebook.  This is my first time trying to use `watchpoints`.  Does it not work with ipython?   Will rework my code to run in a script; in the meantime will leave this post here in case you can help.  Thanks.

**Comment by gaogaotiantian** [comment]
I'm not familiar with ipython but it's very likely that watchpoints does not work with ipython. However, I believe the part that does not work with ipython well is the print, because it's trying to access the file where the changes is written but in ipython it seems like that's not a file.

You can still caught the trigger of the variable change, but you need your own callback function. Check https://github.com/gaogaotiantian/watchpoints#customize-callback for more information. If you still have questions, feel free to ask!

**Comment by gaogaotiantian** [comment]
@DanielGoldfarb oh wait, I think I was wrong. watchpoints can't support any kind of REPL, including ipython, because it's not able to parse the variable name from the file. You have to write a script(a file) to use the feature.

**Comment by gaogaotiantian** [comment]
Hi @DanielGoldfarb, I just checked in the code for REPL support, including ipython. I think you can use it now.

**Comment by DanielGoldfarb** [comment]
@gaogaotiantian 
Thanks.  In the middle of something else right now.  Will try to check it out next week.  Much appreciated.

**Comment by dvirtz** [comment]
It could be nice if it would work with [VSCode python debubger](https://github.com/microsoft/debugpy) as well

**Comment by gaogaotiantian** [comment]
Unfortunately, watchpoints requires source code to work, there's some black magic to make the UI super intuitive. I'm not super familiar with VSCode Python debugger, but there are two things that I'm pretty sure:

1. It compiles the source code as string, so I don't think watchpoints can access the source code
2. It uses sys.settrace to achieve debugger functions, which conflicts with watchpoints because watchpoints uses it as well

Overall, I doubt if watchpoints can be used with VSCode debugger, even with efforts to adapt it.
