### ISSUE TITLE
Output the result in oneline.

### ISSUE THREAD

**Issue by DeadBush225** [gaogaotiantian/watchpoints#26]
I tried to watch my list and it outputs in a horizontal way, one item each line.
I wish it can output in one line so I can compare the list faster.

```====== Watchpoints Triggered ======
Call Stack (most recent call last):
  <module> (D:\OCR\New folder\safe prototype gui.py:449):
>   per_picture.append(fil_result)
per_picture:
[
  [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    '

'
  ]
]
->
[
  [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    '

'
  ],
  [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    '

'
  ]
]```

**Comment by gaogaotiantian** [comment]
``watchpoints`` uses ``objprint`` to print the object as of now. There is currently no easy way to use the default ``print``. One possible way is to customize the callback for ``watchpoints``, it's not that difficult, but may be too much for you(let me know if you want more specifics).

However, I think this is a valid problem to solve, I'll add some configuration options to use the default ``print`` instead of ``objprint``.

**Comment by DeadBush225** [comment]
Thank you for your response. I'm sorry but I'm just  starting up with python so I don't have so much experience with OOP but It's a good idea to add some options to what use between `print` and `objprint`. Let me know if I can help with this.

**Comment by gaogaotiantian** [comment]
I added the ``use_default_print`` feature. It's now in master branch, however it's not released yet.

You can try it out with ``pip install git+https://www.github.com/gaogaotiantian/watchpoints``. If there are no other updates in the next few days, I'll probably release it with 0.2.5

**Comment by DeadBush225** [comment]
It worked! Thank You! I really appreciate your work and it helped me save large amount of time.

**Comment by DeadBush225** [comment]
Hi, Just realized that the defau

**Comment by gaogaotiantian** [comment]
Did you try the list you mentioned? I don't think ``objprint`` prints like this. For the list you mention, it should print everything in one line - 
```
[['a', 'b', 'c', 'd'], ['e', 'f', 'g', 'h'], ['i', 'j', 'k', 'l']]
```
The logic ``objprint`` follows is - try to print everything in a single line, and if it can't, print every element in a separate line.

The main use case for ``objprint`` is to print Python objects, and the majority of them are rather complicated. You gave an example of "single character 2D-list", and in this special situation, yes the display you gave is the best.

However, things could be complicated once the data becomes more complicated. For example, what if it's not a single character 2D list? What if they could be multiple characters? What if it's not a matrix, rather a list of variable-size list? What if the row width is 400 instead of 4?

The safest and most simple way to do it is to display each item in it's own line(or multiple lines). It's true that when the list contains of many single character elements, it may not be as good as the default print, especially when you try to compare them side by side. However, it's actually clearer if you try to locate a single element in the list, and when the structure of the list(or dict/object) got more complicated, you'll see why ``objprint`` stands out.

**Comment by gaogaotiantian** [comment]
Just to clarify, I changed the interface so anyone can use their own printer. Now you can use ``watch(a, custom_printer=print)`` to achieve this feature.
