### ISSUE TITLE
It doesn't seems to work with pdb in terminal?

### ISSUE THREAD

**Issue by MR-hyj** [gaogaotiantian/watchpoints#34]
非常的Amazing as it is, i don't think it can work in a terminal like pdb cuz it is a package...
Personally, I won't be happy if I had to code so much `watch` and `unwatch` and debug over and over and over..

**Comment by gaogaotiantian** [comment]
Unfortunaly that's how `watchpoints` works now. It probably won't work with pdb because there's some black magic behind it to get the variable you are trying to trace, which requires file access. More importantly, it uses `settrace` which conflicts with pdb. So even I can understand your frustration, there's nothing I can do to make you happy at this point.

**Comment by MR-hyj** [comment]
> Unfortunaly that's how `watchpoints` works now. It probably won't work with pdb because there's some black magic behind it to get the variable you are trying to trace, which requires file access. More importantly, it uses `settrace` which conflicts with pdb. So even I can understand your frustration, there's nothing I can do to make you happy at this point.

🤣pitty for pdb not having a `watch` like gdb.
